### ISSUE TITLE
关于浏览器控制台报错失效css

### ISSUE THREAD

**Issue by peg195** [MilBuuket/corbo.github.com#2]
失效css：https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap
地址：/app/scss/style.scss 下的第 8 行
解决方法：删除 /app/scss/style.scss 中的`@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap");`

**Comment by H2OCL-0228** [comment]
alright

**Comment by H2OCL-0228** [comment]
好了

**Comment by H2OCL-0228** [comment]
<img width="960" alt="屏幕截图 2024-02-13 211437" src="https://github.com/MilBuuket/corbo.github.com/assets/159419229/2c0d26d8-faa7-427c-aab4-f5042b860776">
应该可以了
