### ISSUE TITLE
关于浏览器控制台又报错的问题及解决方法（（（

### ISSUE THREAD

**Issue by peg195** [MilBuuket/corbo.github.com#4]
报错：GET https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap net::ERR_ABORTED 502 (Bad Gateway)
解决方法：删除 /dist/style.css 的第 1 行中的`@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap");`

**Comment by H2OCL-0228** [comment]
ok

**Comment by H2OCL-0228** [comment]
**GIT新闻**
**我解决了**
